export const LOGIN = "login"
export const ACTIVATION = "activation"
export const RESET_PASS = "reset-pass"
export const FORGOT_PASS_INIT = "forgot-pass-init"
export const FORGOT_PASS_FINISH = "forgot-pass-finish"
export const CHANGE_PASS = "change-pass"